package main

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"math/cmplx"
	"net/http"
	"os/exec"
	"strconv"
	"strings"
	"time"
)

// analysis.go houses the v0.4.0 "deeper signal inspection" endpoints —
// BPM detection, spectrogram rendering, and bit-depth + spectral-rolloff
// provenance measurement. Same shape as metadata.go: validate path,
// shell out to a tool (or do DSP in pure Go), return JSON/PNG.

// ---------- /bpm ----------

// handleBPM answers `GET /bpm?path=...`. Wraps bpm-tools' `bpm` binary
// — ffmpeg decodes the file to raw 16-bit mono PCM and we pipe that
// into `bpm`, which prints a single tempo value. Powers BPM-aware
// Smart Mixes Cordata-side: natural energy progression instead of
// random shuffle.
type bpmResult struct {
	Version int     `json:"version"`
	BPM     float64 `json:"bpm"`
}

func (s *server) handleBPM(w http.ResponseWriter, r *http.Request) {
	abs, ok := s.validatedPath(w, r)
	if !ok {
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
	defer cancel()

	res, err := computeBPM(ctx, s.computer.ffmpegPath, s.cfg.BpmPath, abs)
	if err != nil {
		http.Error(w, "bpm failed: "+err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(res)
}

func computeBPM(ctx context.Context, ffmpegPath, bpmPath, path string) (*bpmResult, error) {
	// bpm-tools `bpm` reads 32-bit float mono PCM at 44.1 kHz from
	// stdin (Debian package default). We feed ffmpeg's decode straight
	// in. Earlier versions of this code used s16le and got 0-byte
	// responses because bpm silently mis-parses int data as floats.
	decode := exec.CommandContext(ctx, ffmpegPath,
		"-hide_banner", "-loglevel", "error",
		"-i", path,
		"-map", "a:0",
		"-ac", "1",
		"-f", "f32le",
		"-ar", "44100",
		"-",
	)
	var decodeStderr bytes.Buffer
	decode.Stderr = &decodeStderr
	pipe, err := decode.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("ffmpeg pipe: %w", err)
	}

	bpm := exec.CommandContext(ctx, bpmPath)
	bpm.Stdin = pipe
	var bpmOut, bpmErr bytes.Buffer
	bpm.Stdout = &bpmOut
	bpm.Stderr = &bpmErr

	if err := decode.Start(); err != nil {
		return nil, fmt.Errorf("ffmpeg start: %w", err)
	}
	if err := bpm.Start(); err != nil {
		_ = decode.Process.Kill()
		return nil, fmt.Errorf("bpm start: %w", err)
	}
	if err := decode.Wait(); err != nil {
		return nil, fmt.Errorf("ffmpeg exit: %w (stderr: %s)", err, decodeStderr.String())
	}
	if err := bpm.Wait(); err != nil {
		return nil, fmt.Errorf("bpm exit: %w (stderr: %s)", err, bpmErr.String())
	}

	val, err := strconv.ParseFloat(strings.TrimSpace(bpmOut.String()), 64)
	if err != nil {
		return nil, fmt.Errorf("parse bpm output %q: %w", bpmOut.String(), err)
	}
	return &bpmResult{Version: 1, BPM: val}, nil
}

// ---------- /spectrogram ----------

// handleSpectrogram answers `GET /spectrogram?path=...&width=...&height=...`.
// Returns a PNG image generated by sox's spectrogram filter. Width/
// height default to 800x400; clamped to reasonable bounds so a stolen
// token can't ask us to render a 50 000 px image.
//
// Audiophile use: visual-frequency-content per track, which Roon
// doesn't surface. Combined with the provenance endpoint, gives the
// "is this actually high-res?" answer at a glance — upsampled files
// show a hard cliff at the source Nyquist (e.g., 22 kHz line on a
// supposed 96 kHz file).
func (s *server) handleSpectrogram(w http.ResponseWriter, r *http.Request) {
	abs, ok := s.validatedPath(w, r)
	if !ok {
		return
	}

	width, _ := strconv.Atoi(r.URL.Query().Get("width"))
	if width <= 0 {
		width = 800
	}
	if width > 2400 {
		width = 2400
	}
	height, _ := strconv.Atoi(r.URL.Query().Get("height"))
	if height <= 0 {
		height = 400
	}
	if height > 1200 {
		height = 1200
	}

	ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
	defer cancel()

	// sox writes the PNG to a path argument (`-o`); it doesn't stream
	// to stdout. Use a temp file and stream it back.
	tmpPath := fmt.Sprintf("/tmp/cordata-spectrogram-%d.png", time.Now().UnixNano())
	cmd := exec.CommandContext(ctx, s.cfg.SoxPath,
		abs,
		"-n", // null output (spectrogram filter writes the file, not the audio output)
		"spectrogram",
		"-X", strconv.Itoa(width/2), // X pixels per second; rough calibration
		"-y", strconv.Itoa(height),
		"-x", strconv.Itoa(width),
		"-r", // raw — no axes/title, just the spectrogram tile
		"-o", tmpPath,
	)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		http.Error(w, "spectrogram failed: "+err.Error()+" (sox: "+stderr.String()+")",
			http.StatusInternalServerError)
		return
	}
	defer func() { _ = exec.Command("rm", "-f", tmpPath).Run() }()

	w.Header().Set("Content-Type", "image/png")
	w.Header().Set("Cache-Control", "private, max-age=86400")
	if f, err := exec.Command("cat", tmpPath).Output(); err == nil {
		_, _ = w.Write(f)
	} else {
		http.Error(w, "read spectrogram file: "+err.Error(), http.StatusInternalServerError)
	}
}

// ---------- /provenance ----------

// handleProvenance answers `GET /provenance?path=...`. Reports honest
// measurements — no opinions. Cordata draws the "is this upsampled /
// transcoded?" conclusion from the data we give it.
//
// What we measure:
//   - declared_sample_rate / declared_bit_depth: from container metadata
//     (what the file claims)
//   - measured_bit_depth: analyzes raw samples to find the actual lowest
//     significant bit. A 24-bit file padded from 16-bit data has
//     all-zero low 8 bits → measured = 16.
//   - spectral_rolloff_hz: FFT over windows spread through the track,
//     finds the highest frequency with energy above the noise floor.
//     A 96 kHz file upsampled from 44.1 kHz rolls off at ~22 kHz.
type provenanceResult struct {
	Version            int     `json:"version"`
	DeclaredSampleRate int     `json:"declared_sample_rate"`
	DeclaredBitDepth   int     `json:"declared_bit_depth"`
	MeasuredBitDepth   int     `json:"measured_bit_depth"`
	SpectralRolloffHz  float64 `json:"spectral_rolloff_hz"`
}

func (s *server) handleProvenance(w http.ResponseWriter, r *http.Request) {
	abs, ok := s.validatedPath(w, r)
	if !ok {
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
	defer cancel()

	res, err := computeProvenance(ctx, s.computer.ffmpegPath, abs)
	if err != nil {
		http.Error(w, "provenance failed: "+err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(res)
}

func computeProvenance(ctx context.Context, ffmpegPath, path string) (*provenanceResult, error) {
	// Step 1: declared values via ffprobe.
	probe := exec.CommandContext(ctx, "ffprobe",
		"-hide_banner", "-loglevel", "error",
		"-print_format", "json",
		"-show_streams",
		"-select_streams", "a:0",
		path,
	)
	var probeOut, probeErr bytes.Buffer
	probe.Stdout = &probeOut
	probe.Stderr = &probeErr
	if err := probe.Run(); err != nil {
		return nil, fmt.Errorf("ffprobe: %w (stderr: %s)", err, probeErr.String())
	}
	var probeData struct {
		Streams []struct {
			SampleRate    string `json:"sample_rate"`
			BitsPerSample int    `json:"bits_per_sample"`
			BitsPerRaw    string `json:"bits_per_raw_sample"`
			SampleFmt     string `json:"sample_fmt"`
		} `json:"streams"`
	}
	if err := json.Unmarshal(probeOut.Bytes(), &probeData); err != nil {
		return nil, fmt.Errorf("parse ffprobe: %w", err)
	}
	if len(probeData.Streams) == 0 {
		return nil, fmt.Errorf("no audio stream")
	}
	st := probeData.Streams[0]
	declaredRate, _ := strconv.Atoi(st.SampleRate)
	declaredBits := st.BitsPerSample
	if declaredBits == 0 {
		// FLAC reports bits in bits_per_raw_sample; PCM in bits_per_sample.
		declaredBits, _ = strconv.Atoi(st.BitsPerRaw)
	}
	if declaredBits == 0 {
		// Fall back to sample_fmt → s16/s24/s32/flt.
		switch strings.TrimSuffix(st.SampleFmt, "p") {
		case "s16":
			declaredBits = 16
		case "s24":
			declaredBits = 24
		case "s32":
			declaredBits = 32
		case "flt":
			declaredBits = 32
		}
	}

	// Step 2: decode samples to s32le to measure actual bit depth + run
	// FFT for rolloff. s32 captures whatever precision is in the file
	// (FLAC up to 32-bit). Stereo channels are interleaved.
	const measureRate = 0 // 0 = native rate
	decodeRate := strconv.Itoa(declaredRate)
	if measureRate > 0 {
		decodeRate = strconv.Itoa(measureRate)
	}
	decode := exec.CommandContext(ctx, ffmpegPath,
		"-hide_banner", "-loglevel", "error",
		"-i", path,
		"-map", "a:0",
		"-ac", "1",
		"-f", "s32le",
		"-ar", decodeRate,
		"-",
	)
	var decodeStderr bytes.Buffer
	decode.Stderr = &decodeStderr
	pipe, err := decode.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("ffmpeg pipe: %w", err)
	}
	if err := decode.Start(); err != nil {
		return nil, fmt.Errorf("ffmpeg start: %w", err)
	}

	bits, rolloff, err := analyzeSamples(pipe, declaredRate)
	_ = decode.Wait()
	if err != nil {
		return nil, fmt.Errorf("analyze: %w", err)
	}

	return &provenanceResult{
		Version:            1,
		DeclaredSampleRate: declaredRate,
		DeclaredBitDepth:   declaredBits,
		MeasuredBitDepth:   bits,
		SpectralRolloffHz:  rolloff,
	}, nil
}

// analyzeSamples consumes an s32le mono PCM stream and produces:
//   - effectiveBits: the actual bit depth used by the data (analysis of
//     the LSBs across all samples). For a 32-bit container that's
//     actually 16-bit padded data, returns 16.
//   - rolloffHz: highest frequency with FFT magnitude above -100 dB
//     below peak. Averaged across several windows spread through the
//     stream so we sample the whole track, not just one section.
func analyzeSamples(r io.Reader, sampleRate int) (effectiveBits int, rolloffHz float64, err error) {
	const fftSize = 8192             // ~186ms at 44.1k, ~85ms at 96k
	const windowSpacing = 30 * 44100 // sample one window every ~30 sec at 44.1k equivalent
	bitMask := uint32(0)
	windowsAnalyzed := 0
	rolloffSum := 0.0
	curWindow := make([]float64, 0, fftSize)
	samplesSeen := 0
	nextWindowAt := 0

	buf := make([]byte, 8192)
	for {
		n, readErr := r.Read(buf)
		if n > 0 {
			n -= n % 4
			for i := 0; i < n; i += 4 {
				bits := binary.LittleEndian.Uint32(buf[i : i+4])
				// Track which bit positions ever change across all
				// samples. For bit-depth measurement we OR the absolute
				// value of the sample bits — zeros in the low end of
				// every sample mean the file isn't using that precision.
				s := int32(bits)
				abs := uint32(s)
				if s < 0 {
					abs = uint32(-s)
				}
				bitMask |= abs

				// Collect samples for the next FFT window.
				if samplesSeen >= nextWindowAt && len(curWindow) < fftSize {
					curWindow = append(curWindow, float64(s)/2147483648.0)
				}
				if len(curWindow) == fftSize {
					rolloffSum += spectralRolloff(curWindow, sampleRate)
					windowsAnalyzed++
					curWindow = curWindow[:0]
					nextWindowAt = samplesSeen + windowSpacing
				}
				samplesSeen++
			}
		}
		if readErr == io.EOF {
			break
		}
		if readErr != nil {
			return 0, 0, readErr
		}
	}

	// Effective bit depth: find the lowest set bit in bitMask. If
	// bitMask = 0xFFFF0000 the low 16 bits are unused → file is
	// effectively 16-bit (shifted into the high bits of s32).
	if bitMask == 0 {
		effectiveBits = 0 // silent file
	} else {
		// Find lowest set bit index.
		lowest := 0
		for i := 0; i < 32; i++ {
			if bitMask&(1<<i) != 0 {
				lowest = i
				break
			}
		}
		// s32 sample uses bits 0..31; if lowest set is at position L,
		// effective depth is 32 - L. Snap to canonical depths so 1-LSB
		// noise from the ffmpeg stereo→mono downmix doesn't surface as
		// "17 bits" on what's really a 16-bit file.
		raw := 32 - lowest
		switch {
		case raw <= 16:
			effectiveBits = 16
		case raw <= 20:
			effectiveBits = 20
		case raw <= 24:
			effectiveBits = 24
		default:
			effectiveBits = 32
		}
	}

	if windowsAnalyzed > 0 {
		rolloffHz = rolloffSum / float64(windowsAnalyzed)
	}
	return effectiveBits, rolloffHz, nil
}

// spectralRolloff runs a radix-2 FFT on a single window of mono float
// samples (normalized to [-1, 1]) and returns the highest frequency
// bin with energy above -100 dB below the peak bin. That cutoff is
// pessimistic on purpose: dither + reconstruction noise sit ~120 dB
// down, so -100 dB cleanly distinguishes real spectral content from
// noise floor.
func spectralRolloff(samples []float64, sampleRate int) float64 {
	n := len(samples)
	// Apply a Hann window to reduce spectral leakage at the edges of
	// the analysis window — without this an FFT of a short audio chunk
	// has artificial energy across all bins.
	x := make([]complex128, n)
	for i := 0; i < n; i++ {
		hann := 0.5 * (1 - math.Cos(2*math.Pi*float64(i)/float64(n-1)))
		x[i] = complex(samples[i]*hann, 0)
	}
	fft(x)

	// Find peak magnitude across bins 1..N/2 (skip DC).
	half := n / 2
	maxMag := 0.0
	for i := 1; i < half; i++ {
		m := cmplx.Abs(x[i])
		if m > maxMag {
			maxMag = m
		}
	}
	if maxMag == 0 {
		return 0
	}
	threshold := maxMag * 1e-5 // -100 dB below peak

	// Highest bin above threshold.
	highest := 0
	for i := 1; i < half; i++ {
		if cmplx.Abs(x[i]) > threshold {
			highest = i
		}
	}
	return float64(highest) * float64(sampleRate) / float64(n)
}

// fft does an in-place iterative radix-2 Cooley-Tukey FFT. Requires
// len(x) to be a power of 2. We always pass fftSize=8192, so this is
// safe — no length check at runtime to keep the hot path tight.
func fft(x []complex128) {
	n := len(x)
	// Bit-reverse permutation.
	j := 0
	for i := 1; i < n; i++ {
		bit := n >> 1
		for ; j&bit != 0; bit >>= 1 {
			j ^= bit
		}
		j ^= bit
		if i < j {
			x[i], x[j] = x[j], x[i]
		}
	}
	// Butterflies.
	for length := 2; length <= n; length <<= 1 {
		angle := -2 * math.Pi / float64(length)
		wlen := cmplx.Rect(1, angle)
		for i := 0; i < n; i += length {
			w := complex(1, 0)
			half := length / 2
			for k := 0; k < half; k++ {
				u := x[i+k]
				v := x[i+k+half] * w
				x[i+k] = u + v
				x[i+k+half] = u - v
				w *= wlen
			}
		}
	}
}
